import type { Language } from "./domain/types";

export const dict = {
  th: {
    sales:"ขาย", products:"สินค้าและสต็อก", history:"รายการขาย", reports:"รายงาน", employees:"พนักงาน", settings:"ตั้งค่า",
    loading:"กำลังเตรียมระบบ...", loadingDb:"กำลังโหลดฐานข้อมูล...", loadingShift:"กำลังตรวจสอบกะ...", dbError:"เปิดระบบไม่สำเร็จ", loginTitle:"เข้าสู่ระบบขายหน้าร้าน", loginHint:"กรอกรหัสพนักงานและ PIN", pinWrong:"PIN ไม่ถูกต้อง", employeeCode:"รหัสพนักงาน",
    openShift:"เปิดกะการขาย", openingCash:"เงินสดตั้งต้น", open:"เปิดกะ", offlineReady:"OFFLINE READY", closeShift:"ปิดกะ", closeShiftTitle:"สรุปก่อนปิดกะ", confirmCloseShift:"ยืนยันปิดกะ", closedToLogin:"หลังปิดกะ ระบบจะกลับไปหน้าเข้าสู่ระบบ", back:"กลับ",
    scan:"สแกนบาร์โค้ด", search:"ค้นหาสินค้า", all:"ทั้งหมด", cart:"ตะกร้า", emptyCart:"ยังไม่มีสินค้า", pay:"ชำระเงิน", checkout:"ชำระเงิน", cancelBill:"ยกเลิกรายการที่ยังไม่ชำระ", total:"ยอดชำระ", cash:"เงินสด", transfer:"เงินโอน", promptpay:"PromptPay", card:"บัตร", recordOnly:"ระบบบันทึกวิธีชำระเงินเท่านั้น กรุณาตรวจสอบยอดเงินจริงก่อนยืนยัน", received:"รับเงิน", change:"เงินทอน", confirm:"ยืนยัน", confirmPayment:"ยืนยันรับชำระ", close:"ปิด", save:"บันทึก", edit:"แก้ไข", addProduct:"เพิ่มสินค้า", openExisting:"เปิดสินค้านี้", duplicateBarcode:"บาร์โค้ดซ้ำกับสินค้าเดิม", duplicateCode:"รหัสสินค้าซ้ำ", unknownBarcode:"ไม่พบสินค้าสำหรับบาร์โค้ดนี้", productCode:"รหัสสินค้า", barcode:"Barcode", nameTh:"ชื่อไทย", nameEn:"English name", category:"หมวดหมู่", price:"ราคาขาย", cost:"ต้นทุน", unit:"หน่วย", stock:"คงเหลือ", minStock:"ขั้นต่ำ", active:"เปิดขาย", inactive:"ปิดขาย", image:"รูปสินค้า", productInfo:"ข้อมูลสินค้า", pricing:"ราคา", stockSection:"สต็อก", status:"สถานะ", stockIn:"รับเข้า", stockOut:"ตัดออก", adjustment:"ปรับยอด", reason:"เหตุผล", voidSale:"VOID บิลที่ชำระแล้ว", restockReturned:"รับสินค้ากลับเข้าสต็อก", language:"ภาษา", thai:"ไทย", english:"English", receipt:"ใบเสร็จ", reprint:"พิมพ์ซ้ำ", saleStored:"บันทึกขายใน SQLite แล้ว", noInternet:"ไม่ต้องใช้อินเทอร์เน็ต/Supabase/Vercel สำหรับธุรกรรมนี้", storage:"ข้อมูลและพื้นที่", audit:"Audit", demoPin:"PIN ถูกจัดเก็บแบบ hash ในเครื่อง และควรเปลี่ยน PIN เริ่มต้นทันที", exactAmount:"ยอดพอดี", add:"เพิ่ม", empty:"ยังไม่มีข้อมูล", today:"วันนี้", allSales:"ทั้งหมด", cancelledBills:"บิลยกเลิก", recentSales:"รายการล่าสุด", byProduct:"ขายตามสินค้า", byEmployee:"ขายตามพนักงาน", normal:"ปกติ", lowStock:"ใกล้หมด", outOfStock:"หมด", notReady:"ยังไม่พร้อมใช้งาน", storeInfo:"ข้อมูลร้าน", branchDevice:"สาขา / เครื่อง", owner:"เจ้าของร้าน", receiptSettings:"ใบเสร็จ", printer:"เครื่องพิมพ์", scanner:"เครื่องอ่านบาร์โค้ด", backupRestore:"Backup / Restore", remoteManagement:"Remote Management", versionAbout:"เวอร์ชัน / เกี่ยวกับ", role:"สิทธิ์", currentShift:"กะปัจจุบัน", cashier:"แคชเชียร์", paymentMethod:"วิธีชำระ", completed:"COMPLETED", cancelled:"CANCELLED", voided:"VOID", amount:"จำนวน", submitBusy:"กำลังบันทึก..."
  },
  en: {
    sales:"Sales", products:"Products & Stock", history:"Sales History", reports:"Reports", employees:"Employees", settings:"Settings",
    loading:"Preparing system...", loadingDb:"Loading database...", loadingShift:"Checking shift...", dbError:"Could not open application", loginTitle:"POS Login", loginHint:"Enter employee code and PIN", pinWrong:"Wrong PIN", employeeCode:"Employee code",
    openShift:"Open Shift", openingCash:"Opening cash", open:"Open Shift", offlineReady:"OFFLINE READY", closeShift:"Close Shift", closeShiftTitle:"Shift Summary", confirmCloseShift:"Confirm Close Shift", closedToLogin:"After closing the shift, the app returns to login", back:"Back",
    scan:"Scan barcode", search:"Search products", all:"All", cart:"Cart", emptyCart:"Cart is empty", pay:"Payment", checkout:"Checkout", cancelBill:"Cancel unpaid cart", total:"Amount due", cash:"Cash", transfer:"Transfer", promptpay:"PromptPay", card:"Card", recordOnly:"Payment method recording only. Verify real payment before confirming.", received:"Received", change:"Change", confirm:"Confirm", confirmPayment:"Confirm payment", close:"Close", save:"Save", edit:"Edit", addProduct:"Add Product", openExisting:"Open existing", duplicateBarcode:"Barcode already belongs to another product", duplicateCode:"Product code already exists", unknownBarcode:"No product found for this barcode", productCode:"Product code", barcode:"Barcode", nameTh:"Thai name", nameEn:"English name", category:"Category", price:"Selling price", cost:"Cost", unit:"Unit", stock:"Stock", minStock:"Min stock", active:"Active", inactive:"Inactive", image:"Image", productInfo:"Product info", pricing:"Pricing", stockSection:"Stock", status:"Status", stockIn:"Stock in", stockOut:"Stock out", adjustment:"Adjustment", reason:"Reason", voidSale:"Void paid sale", restockReturned:"Return goods to stock", language:"Language", thai:"Thai", english:"English", receipt:"Receipt", reprint:"Reprint", saleStored:"Sale stored in local SQLite", noInternet:"No Internet/Supabase/Vercel API is required for this transaction", storage:"Data & storage", audit:"Audit", demoPin:"PINs are stored as local hashes. Change the initial PIN immediately.", exactAmount:"Exact amount", add:"Add", empty:"No data", today:"Today", allSales:"All sales", cancelledBills:"Cancelled", recentSales:"Recent sales", byProduct:"Sales by product", byEmployee:"Sales by employee", normal:"Normal", lowStock:"Low", outOfStock:"Out", notReady:"Not ready", storeInfo:"Store info", branchDevice:"Branch / Device", owner:"Owner", receiptSettings:"Receipt", printer:"Printer", scanner:"Barcode scanner", backupRestore:"Backup / Restore", remoteManagement:"Remote Management", versionAbout:"Version / About", role:"Role", currentShift:"Current shift", cashier:"Cashier", paymentMethod:"Payment method", completed:"COMPLETED", cancelled:"CANCELLED", voided:"VOID", amount:"Amount", submitBusy:"Saving..."
  }
} as const;

export type TextKey = keyof typeof dict.th;
export const t = (language: Language, key: TextKey) => dict[language]?.[key] ?? dict.th[key];
export const productName = (language: Language, p: { nameTh?: string; nameEn?: string; name?: string }) => language === "en" && p.nameEn ? p.nameEn : p.nameTh || p.name || "";
